spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/security_prac_db?serverTimezone=Asia/Seoul
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  output:
    ansi:
      enabled: always